# dataSource:
#     driverClassName: org.h2.Driver
#     dbCreate: update
#     username: root
#     password: ''

# environments:
#     development:
#         dataSource:
#             dbCreate: update
#             url: "jdbc:mysql://localhost/project?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimeszoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"